print(9 + 7)
print(37 - 24)   
print(5 * 5)   
print(10 / 2)   
print(4 ** 2)  
print(56 % 4)  
print(8 // 2)

print(type(20))                  
print(type(10.14))                
print(type(7 + 8j))              
print(type('Juanito Pistolas'))          
print(type([7, 5, 4]))           
print(type({'Pedro Navajas':'Checoslovaquia'})) 
print(type({10.8, 5.12, 2.7}))    
print(type((7.5, 4.2, 7.2)))    
print(type(4 == 3))              
print(type(48 >= 3))    
print(type([ricadio', Python', Durango]))